language: r
sudo: false
cache: packages
latex: false

branches:
  only:
    - master
    - cran

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    - _R_CHECK_FORCE_SUGGESTS_: false

after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'covr::codecov()'
